(function(g){var window=this;'use strict';var tdb=function(a){g.T.call(this,{G:"div",K:"ytp-inline-preview-ui"});this.Qf=!1;this.player=a;this.N(a,"onStateChange",this.XN);this.N(a,"videodatachange",this.Uo);this.N(a,"onInlinePreviewModeChange",this.R1);this.cf=new g.Un(this.bv,null,this);g.E(this,this.cf)},V5=function(a){g.VQ.call(this,a);
this.j=new tdb(this.player);g.E(this,this.j);this.j.hide();g.mQ(this.player,this.j.element,4);a.isInline()&&(this.load(),g.io(a.getRootNode(),"ytp-inline-preview-mode",!0),this.player.V().S("web_rounded_containers")&&g.io(a.getRootNode(),"ytp-rounded-inline-preview",!0),this.player.V().S("web_inline_player_disable_scrubbing")&&g.io(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0))};
g.v(tdb,g.T);g.k=tdb.prototype;
g.k.eL=function(){this.tooltip=new g.aV(this.player,this);g.E(this,this.tooltip);g.mQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Pc=new g.OR(this.player);g.E(this,this.Pc);var a=["ytp-inline-preview-scrim"];this.player.V().S("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.cj=new g.T({G:"div",Ga:a});g.E(this,this.cj);this.cj.Ca(this.element);this.N(this.cj.element,"click",this.cG);this.player.V().S("web_inline_player_expand_to_watch")&&(a=new g.y2(this.player,
this),g.E(this,a),a.Ca(this.cj.element));this.gj=new g.OU(this.player,this);g.E(this,this.gj);this.gj.Ca(this.cj.element);this.controls=new g.T({G:"div",K:"ytp-inline-preview-controls"});g.E(this,this.controls);this.controls.Ca(this.element);a=new g.qT(this.player,this);g.E(this,a);a.Ca(this.controls.element);a=new g.MU(this.player,this);g.E(this,a);a.Ca(this.controls.element);this.Jc=new g.FT(this.player,this);g.E(this,this.Jc);g.mQ(this.player,this.Jc.element,4);this.N(this.player,"appresize",this.Cb);
this.N(this.player,"fullscreentoggled",this.Cb);this.Cb()};
g.k.show=function(){g.Vn(this.cf);this.Qf||(this.eL(),this.Qf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show()};
g.k.hide=function(){this.cf.stop();g.T.prototype.hide.call(this);this.player.isInline()||this.Qf&&this.Jc.hide()};
g.k.ra=function(){g.T.prototype.ra.call(this)};
g.k.cG=function(a){a.target!==this.cj.element||this.player.V().S("web_inline_player_expand_to_watch")||this.player.Oa("onExpandInlinePreview",a)};
g.k.R1=function(){g.io(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ie=function(){this.Jc.vc();this.gj.vc()};
g.k.bv=function(){this.Ie();g.Vn(this.cf)};
g.k.Cb=function(){g.ZT(this.Jc,0,this.player.fb().getPlayerSize().width,!1);g.IT(this.Jc)};
g.k.XN=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.Uo=function(a,b){if(this.player.isInline()&&(g.io(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.KH),this.player.S("web_player_disable_inline_scrubbing")||this.player.S("disable_inline_preview_scrubbing_for_vac_ads_on_web"))){var c,d;a=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig;c=!0;void 0!==(null==a?void 0:a.showScrubbingControls)&&(c=!!a.showScrubbingControls);g.io(this.player.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",
!c)}};
g.k.Cc=function(){return this.tooltip};
g.k.fg=function(){return!1};
g.k.Yg=function(){return!1};
g.k.vk=function(){return!1};
g.k.Qe=function(){return!1};
g.k.zl=function(){return!1};
g.k.EC=function(){};
g.k.Ap=function(){};
g.k.wx=function(){};
g.k.xm=function(){return null};
g.k.JE=function(){return null};
g.k.ZA=function(){return null};
g.k.nk=function(){return new g.ul(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.wv=function(a,b,c,d,e){var f=d=0,h=0,l=g.Il(a);if(b){c=g.co(b,"ytp-miniplayer-expand-watch-page-button");var m=g.co(b,"ytp-mute-button"),n=g.co(b,"ytp-subtitles-button"),p=g.Gl(b,this.element);b=g.Il(b);d=p.y+40;c&&(h=8);if(n||m)h=p.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.fb().getPlayerSize().width;h=g.ce(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.Qo=function(){};
g.k.ul=function(){return!1};
g.k.FC=function(){};
g.k.Py=function(){};
g.k.Aq=function(){};
g.k.zq=function(){};
g.k.OD=function(){};
g.k.yr=function(){};g.v(V5,g.VQ);V5.prototype.Ik=function(){return!1};
V5.prototype.load=function(){this.player.hideControls();this.j.show()};
V5.prototype.unload=function(){this.player.showControls();this.j.hide()};g.UQ("inline_preview",V5);})(_yt_player);
